# Generated by Django 5.2.7 on 2025-10-22 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='url',
        ),
        migrations.AddField(
            model_name='adkeyword',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datasource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='niche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.niche'),
        ),
        migrations.AddField(
            model_name='trend',
            name='source',
            field=models.CharField(default='multiple', max_length=50),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(choices=[('google_trends', 'Google Trends'), ('amazon', 'Amazon Products'), ('twitter', 'Twitter Trends'), ('reddit', 'Reddit'), ('news', 'News'), ('youtube', 'YouTube')], max_length=50),
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('cleaned_data', models.JSONField(blank=True, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('sentiment', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niche')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datasource')),
            ],
            options={
                'indexes': [models.Index(fields=['niche', 'created_at'], name='core_scrape_niche_i_90a262_idx'), models.Index(fields=['source', 'created_at'], name='core_scrape_source__611c9c_idx')],
            },
        ),
    ]
